name: fifth-season-windows-cuda
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - pandas<2.2
  - xarray
  - matplotlib
  - netcdf4
  - dask
  - scipy
  - scikit-image
  - jupyter
  - ipykernel
  - pip:
      - tensorflow==2.10.*